### ISSUE TITLE
command not found: complete

### ISSUE THREAD

**Issue by gimbo** [macunha1/zsh-terraform#2]
When I try to use this plugin, I see the error:

```
command not found: complete
```

Apparently triggered by [the final line of the plugin](https://github.com/macunha1/zsh-terraform/blob/9469a5c4df297ef4d7079a95b1fad2624f686e4d/terraform.zsh#L52).

I haven't tried this with ohmyzsh (as I don't use it) but I get the error vs a vanilla zsh using [the "git clone" instructions](https://github.com/macunha1/zsh-terraform#manual-git-clone); e.g. here's a Dockerfile for trying this out:

```Dockerfile
FROM zshusers/zsh

RUN apt update
RUN apt install -y git
RUN git clone https://github.com/macunha1/zsh-terraform /root/.zsh/zsh-terraform
RUN echo "source ~/.zsh/zsh-terraform/terraform.zsh" > /root/.zshrc
```

This builds OK:

```shell
$ docker build -t testbed .
...
```

But when run, we get the same error (though aliases are set up properly):

```shell
$ docker run --rm -it testbed
/root/.zsh/zsh-terraform/terraform.zsh:52: command not found: complete
4cdec324e659# alias tf
tf=terraform
4cdec324e659#
```

Any ideas?

**Comment by macunha1** [comment]
That function is provided by loading `bashcompinit` which provides backward (bash) compatible `complete`.

Ref: https://zsh.sourceforge.io/Doc/Release/Completion-System.html#:~:text=The%20function%20bashcompinit%20provides%20compatibility,builtins%20with%20the%20same%20names.

Then `complete` is used (like you mentioned) to load Terraform's completion at that last line.

You can see how I am implementing that at https://github.com/macunha1/configuration.nix/blob/master/config/zsh/.zshrc#L46

```zsh
autoload -U +X bashcompinit && bashcompinit
```

**Comment by macunha1** [comment]
@gimbo addressed the issue you mentioned in the last change pushed to `master`.

Feel free to re-open in case you keep facing errors

**Comment by gimbo** [comment]
LGTM —  many thanks! 🙏
